name: Deploy reactNoteCrudAWSEC2-frontend 

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build Docker Image
        run: docker build -t sergio7174/reactnotescrud-frontend .
      - name: Publish Image to docker hub
        run: docker push sergio7174/reactnotescrud-frontend:latest
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull image from docker hub
        run: docker pull sergio7174/reactnotescrud-frontend:latest
      - name: Delete old container
        run: docker rm -f reactnotescrud-frontend
      - name: Run Docker Container
        run: docker run -d -p 3300:80 --name reactnotescrud-frontend sergio7174/reactnotescrud-frontend